server:
  port: 8085

# Docker: postgres-container and redis-contrainer
spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgres-container:5432/postgres"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  coingecko:
    host:
      demo: "api.coingecko.com"
      pro: "pro-api.coingecko.com"
    api:
      key-name: "x-cg-demo-api-key"
      key-value: "CG-NwCy3TmdJv6BKZwCEAHfuVxp"
      markets:
        version: "api/v3"
        endpoint: "/coins/markets"

spring:
  data:
    redis:
      host: redis-container
      port: 6379