# yml is something like a configuration file

service-url:
  users: "https://jsonplaceholder.typicode.com/users"
  posts: "https://jsonplaceholder.typicode.com/posts"
  comments: "https://jsonplaceholder.typicode.com/comments"